#!/usr/bin/env bash
# installs nginx and configures it on a remote server

sudo apt-get update -y
sudo apt-get install nginx -y
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
sudo service nginx reload
